#pragma once

#include "genpybind.h"
#include "typedefs_definition.h"

// This example demonstrates a typedef to a type that is exposed in a
// different module (generated by a separate call to genpybind with a
// different set of tags).  Note that the other module is included
// explicitly s.t. its definitions will be available at runtime.

GENPYBIND_MANUAL({ parent->py::module::import("pytypedefs_definition"); })

typedef definition::Definition alias GENPYBIND(visible);
typedef definition::Typedef alias_for_typedef GENPYBIND(visible);
