#pragma once

#include "genpybind.h"
#include "typedefs_definition.h"

// This example demonstrates a typedef to a type that is exposed in a
// different module (generated by a separate call to genpybind with a
// different set of tags).  Note that the other module is NOT included
// explicitly s.t. its definitions will NOT be available at runtime
// unless it is imported before this module itself is imported.

typedef definition::Definition alias GENPYBIND(visible);
